jwt:
  key1: fdsuifhewhfewhewjofirehiurehitugreiut32432dffioer
  key2: fuidhgfierjgfiueruhgieurfuewfuewiorhf9efu43tr48rt
  key3: fudijfh87e49rt3842iruf43werjdf938rfy89frhy437uetr
kakao:
  secret: a896dab122730eddfedaccafd66121b3
  redirect_uri: http://localhost:8080/login