spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include:
      - secret
      - jpa
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8080

