spring:
  datasource:
    url: db-ejhi2.pub-cdb.ntruss.com:3306/moyora-db
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
  h2:
    console:
      enabled: true
