spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: com.hexconiac.zoopitoserverkotlin.global.dialect.MySql8DialectCustom
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
  file:
    name: ${user.home}/logs/zoopito.log